# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

# update go modules
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/fix/golang" # Location of package manifests
    schedule:
      interval: "weekly"

# Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/fix/golang"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
